# pylint: disable=R0801,C0103
# Generated by Django 4.2.11 on 2024-06-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FileExtractInfo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=255, unique=True, verbose_name="Key")),
                ("file_path", models.TextField(verbose_name="File Path")),
                ("upload_info", models.JSONField(blank=True, null=True, verbose_name="Upload Info")),
                ("extract_info", models.JSONField(blank=True, null=True, verbose_name="Extract Info")),
                ("is_finished", models.BooleanField(db_index=True, default=False, verbose_name="Is Finished")),
                ("is_success", models.BooleanField(db_index=True, default=False, verbose_name="Is Success")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created At")),
            ],
            options={
                "verbose_name": "File Extract Info",
                "verbose_name_plural": "File Extract Info",
                "ordering": ["-id"],
            },
        ),
    ]
