# pylint: disable=R0801,C0103
# Generated by Django 4.2.17 on 2024-12-19 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cos", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FileExtractInfo",
        ),
    ]
