# pylint: disable=R0801,C0103
# Generated by Django 4.2.13 on 2024-07-02 06:11

import django.db.models.deletion
import ovinc_client.core.models
import ovinc_client.core.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    ovinc_client.core.models.UniqIDField(
                        default=ovinc_client.core.utils.uniq_id_without_time,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("balance", models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name="Balance")),
                (
                    "user",
                    models.OneToOneField(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wallet",
                "verbose_name_plural": "Wallet",
                "ordering": ["user"],
            },
        ),
        migrations.CreateModel(
            name="BillingHistory",
            fields=[
                (
                    "id",
                    ovinc_client.core.models.UniqIDField(
                        default=ovinc_client.core.utils.uniq_id_without_time,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField(verbose_name="Amount")),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SUCCESS", "Success"),
                            ("REFUND", "Refund"),
                            ("NOTPAY", "Not Pay"),
                            ("CLOSED", "Closed"),
                            ("REVOKED", "Revoked"),
                            ("USERPAYING", "User Paying"),
                            ("PAYERROR", "Pay Error"),
                        ],
                        max_length=32,
                        null=True,
                        verbose_name="Message",
                    ),
                ),
                ("is_success", models.BooleanField(default=False, verbose_name="Is Success")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("callback_at", models.DateTimeField(blank=True, null=True, verbose_name="Callback Time")),
                ("callback_data", models.JSONField(blank=True, null=True, verbose_name="Callback Data")),
                (
                    "user",
                    ovinc_client.core.models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Billing History",
                "verbose_name_plural": "Billing History",
                "ordering": ["-created_at"],
                "index_together": {("user", "created_at")},
            },
        ),
    ]
