# pylint: disable=R0801,C0103
# Generated by Django 4.2.3 on 2024-02-27 05:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0006_aimodel_is_vision_aimodel_vision_quality_and_more"),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name="modelpermission",
            index_together={("user", "model", "expired_at")},
        ),
        migrations.AddField(
            model_name="modelpermission",
            name="available_usage",
            field=models.BigIntegerField(db_index=True, default=int, verbose_name="Available Usage"),
        ),
        migrations.AlterIndexTogether(
            name="modelpermission",
            index_together={("user", "available_usage", "model", "expired_at"), ("user", "model", "expired_at")},
        ),
    ]
