# pylint: disable=R0801,C0103
# Generated by Django 4.2.3 on 2024-02-27 05:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0007_alter_modelpermission_index_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="modelpermission",
            unique_together={("user", "model")},
        ),
    ]
