# pylint: disable=R0801,C0103
# Generated by Django 4.2.3 on 2024-02-27 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_alter_aimodel_vision_size_alter_aimodel_vision_style_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatlog",
            name="is_charged",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Is Charged"),
        ),
    ]
