# pylint: disable=R0801,C0103
# Generated by Django 4.2.3 on 2024-02-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0009_chatlog_is_charged_alter_aimodel_vision_size_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aimodel",
            name="vision_size",
            field=models.CharField(
                blank=True, choices=[("1024x1024", "1024x1024")], max_length=64, null=True, verbose_name="Vision Size"
            ),
        ),
        migrations.AlterField(
            model_name="aimodel",
            name="vision_style",
            field=models.CharField(
                blank=True,
                choices=[("vivid", "Vivid"), ("natural", "Natural")],
                max_length=64,
                null=True,
                verbose_name="Vision Style",
            ),
        ),
        migrations.AlterIndexTogether(
            name="chatlog",
            index_together={("finished_at", "is_charged")},
        ),
    ]
