# pylint: disable=R0801,C0103
# Generated by Django 4.2.11 on 2024-04-27 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0010_alter_aimodel_vision_size_alter_aimodel_vision_style_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aimodel",
            name="currency_unit",
            field=models.CharField(
                choices=[("$", "USD($)"), ("¥", "RMB(¥)")], default="$", max_length=32, verbose_name="Currency Unit"
            ),
        ),
        migrations.AddField(
            model_name="chatlog",
            name="currency_unit",
            field=models.CharField(
                choices=[("$", "USD($)"), ("¥", "RMB(¥)")], default="$", max_length=32, verbose_name="Currency Unit"
            ),
        ),
    ]
