# Generated by Django 4.2.11 on 2024-06-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0012_aimodel_settings_alter_aimodel_provider"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatlog",
            name="content",
        ),
        migrations.RemoveField(
            model_name="chatlog",
            name="messages",
        ),
        migrations.AlterField(
            model_name="aimodel",
            name="provider",
            field=models.CharField(
                choices=[
                    ("openai", "Open AI"),
                    ("google", "Google"),
                    ("baidu", "Baidu"),
                    ("tencent", "Tencent"),
                    ("aliyun", "Aliyun"),
                    ("moonshot", "Moonshot"),
                ],
                db_index=True,
                max_length=64,
                verbose_name="Provider",
            ),
        ),
    ]
