# Generated by Django 4.2.11 on 2024-06-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0013_remove_chatlog_content_remove_chatlog_messages_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aimodel",
            name="desc",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
    ]
