# pylint: disable=R0801,C0103
# Generated by Django 4.2.11 on 2024-06-29 09:45

import django.db.models.deletion
import ovinc_client.core.models
import ovinc_client.core.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0014_aimodel_desc"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemPreset",
            fields=[
                (
                    "id",
                    ovinc_client.core.models.UniqIDField(
                        default=ovinc_client.core.utils.uniq_id_without_time,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                ("content", models.TextField(verbose_name="Content")),
                ("is_public", models.BooleanField(db_index=True, default=False, verbose_name="Is Public")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Create Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Update Time")),
                (
                    "user",
                    ovinc_client.core.models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "System Preset",
                "verbose_name_plural": "System Preset",
                "ordering": ["-created_at"],
                "index_together": {("is_public", "user", "name")},
            },
        ),
    ]
