# pylint: disable=R0801,C0103
# Generated by Django 4.2.11 on 2024-06-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0015_systempreset"),
    ]

    operations = [
        migrations.AddField(
            model_name="aimodel",
            name="support_system_define",
            field=models.BooleanField(default=True, verbose_name="Support System Define"),
        ),
    ]
