# pylint: disable=R0801,C0103
# Generated by Django 4.2.13 on 2024-07-02 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0017_remove_aimodel_currency_unit_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ModelPermission",
        ),
    ]
