# pylint: disable=R0801,C0103
# Generated by Django 4.2.13 on 2024-07-02 10:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0018_delete_modelpermission"),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name="chatlog",
            index_together={("user", "finished_at", "created_at"), ("finished_at", "is_charged")},
        ),
    ]
