# pylint: disable=R0801,C0103
# Generated by Django 4.2.17 on 2024-12-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0020_aimodel_support_vision_alter_aimodel_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="aimodel",
            name="vision_price",
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name="Vision Price"),
        ),
        migrations.AlterField(
            model_name="aimodel",
            name="provider",
            field=models.CharField(
                choices=[
                    ("openai", "Open AI"),
                    ("google", "Google"),
                    ("tencent", "Tencent"),
                    ("midjourney", "Midjourney"),
                    ("claude", "Claude"),
                    ("zhipu", "Zhipu"),
                ],
                db_index=True,
                max_length=64,
                verbose_name="Provider",
            ),
        ),
    ]
