# pylint: disable=R0801,C0103
# Generated by Django 4.2.17 on 2024-12-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0021_aimodel_vision_price_alter_aimodel_provider"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aimodel",
            name="vision_quality",
        ),
        migrations.RemoveField(
            model_name="aimodel",
            name="vision_size",
        ),
        migrations.RemoveField(
            model_name="aimodel",
            name="vision_style",
        ),
        migrations.AlterField(
            model_name="aimodel",
            name="provider",
            field=models.CharField(
                choices=[("openai", "Open AI"), ("midjourney", "Midjourney")],
                db_index=True,
                max_length=64,
                verbose_name="Provider",
            ),
        ),
    ]
