# pylint: disable=R0801,C0103
# Generated by Django 4.2.17 on 2024-12-20 09:00

import django.db.models.deletion
import ovinc_client.core.models
import ovinc_client.core.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0022_remove_aimodel_vision_quality_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aimodel",
            name="is_public",
            field=models.BooleanField(default=True, verbose_name="Is Public"),
        ),
        migrations.CreateModel(
            name="ModelPermission",
            fields=[
                (
                    "id",
                    ovinc_client.core.models.UniqIDField(
                        default=ovinc_client.core.utils.uniq_id_without_time,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "models",
                    models.ManyToManyField(
                        db_constraint=False, related_name="model_permissions", to="chat.aimodel", verbose_name="Model"
                    ),
                ),
                (
                    "user",
                    ovinc_client.core.models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_permissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Model Permission",
                "verbose_name_plural": "Model Permission",
                "ordering": ["user"],
            },
        ),
    ]
