# pylint: disable=R0801,C0103
# Generated by Django 4.2.17 on 2024-12-20 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0023_aimodel_is_public_modelpermission"),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name="aimodel",
            index_together={("is_enabled", "is_public", "model")},
        ),
    ]
