# pylint: disable=R0801,C0103
# Generated by Django 4.2.17 on 2024-12-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0024_alter_aimodel_index_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="aimodel",
            name="request_price",
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name="Request Price"),
        ),
        migrations.AddField(
            model_name="chatlog",
            name="request_unit_price",
            field=models.DecimalField(
                decimal_places=10, default=float, max_digits=20, verbose_name="Request Unit Price"
            ),
        ),
        migrations.AddField(
            model_name="chatlog",
            name="vision_count",
            field=models.BigIntegerField(default=int, verbose_name="Vision Count"),
        ),
        migrations.AddField(
            model_name="chatlog",
            name="vision_unit_price",
            field=models.DecimalField(
                decimal_places=10, default=float, max_digits=20, verbose_name="Vision Unit Price"
            ),
        ),
        migrations.AlterField(
            model_name="aimodel",
            name="completion_price",
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name="Completion Price"),
        ),
        migrations.AlterField(
            model_name="aimodel",
            name="is_public",
            field=models.BooleanField(default=False, verbose_name="Is Public"),
        ),
        migrations.AlterField(
            model_name="aimodel",
            name="prompt_price",
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name="Prompt Price"),
        ),
        migrations.AlterField(
            model_name="chatlog",
            name="completion_tokens",
            field=models.BigIntegerField(default=int, verbose_name="Completion Tokens"),
        ),
        migrations.AlterField(
            model_name="chatlog",
            name="prompt_tokens",
            field=models.BigIntegerField(default=int, verbose_name="Prompt Tokens"),
        ),
    ]
