# pylint: disable=R0801,C0103
# Generated by Django 4.2.17 on 2024-12-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0025_aimodel_request_price_chatlog_request_unit_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aimodel",
            name="icon",
            field=models.URLField(blank=True, null=True, verbose_name="Icon"),
        ),
    ]
