# pylint: disable=R0801,C0103
# Generated by Django 4.2.17 on 2025-02-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0028_chatmessagechangelog_chat_chatme_user_id_87507d_idx"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aimodel",
            name="is_vision",
        ),
        migrations.AlterField(
            model_name="aimodel",
            name="provider",
            field=models.CharField(
                choices=[("openai", "Open AI")], db_index=True, max_length=64, verbose_name="Provider"
            ),
        ),
    ]
